[config.wallpaper]
command = "true"  
set = false

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.kitty]
input_path = "/home/kush/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/matugen.conf"
post_hook = "pkill -SIGUSR1 kitty"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell.qml"
output_path = "~/.config/quickshell/modules/Theme.qml"

[templates.niri]
input_path = "~/.config/matugen/templates/niri-colors.kdl"
output_path = "~/.config/niri/colors.kdl"
