-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#181616",
	base01 = "#1b1919",
	base02 = "#201e1e",
	base03 = "#3f3d39",
	base04 = "#c8c093",
	base05 = "#c5c9c5",
	base06 = "#282424",
	base07 = "#474545",

	base08 = "#c4746e",
	base09 = "#c4746e",
	base0A = "#8ea4a2",
	base0B = "#8a9a7b",
	base0C = "#64201b",
	base0D = "#313f23",
	base0E = "#2f504d",
	base0F = "#64201b",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#313f23",
	fg = "#181616",
})

set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#f0dcdb",
})

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#c4746e",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#8ea4a2",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "#649933",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "#1b1919",
	fg = "#8a9a7b",
})
