-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#161616",
	base01 = "#191919",
	base02 = "#1e1e1e",
	base03 = "#3d3d3d",
	base04 = "#dde1e6",
	base05 = "#f2f4f8",
	base06 = "#282424",
	base07 = "#454545",

	base08 = "#ee5396",
	base09 = "#be95ff",
	base0A = "#42be65",
	base0B = "#33b1ff",
	base0C = "#5700e2",
	base0D = "#004f80",
	base0E = "#0e3f1c",
	base0F = "#8c023e",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#004f80",
	fg = "#161616",
})

set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#e0ccff",
})

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#be95ff",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#42be65",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "#1479b8",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "#191919",
	fg = "#33b1ff",
})
