# --- Main Colors ---
background            {bg}
foreground            {fg}
cursor                {fg}
cursor_text_color     {bg}

selection_background  {surface}
selection_foreground  {fg}

url_color             {accent}

# --- ANSI Colors ---
color0                {color0}
color1                {color1}
color2                {color2}
color3                {color3}
color4                {color4}
color5                {color5}
color6                {color6}
color7                {color7}

color8                {color8}
color9                {color9}
color10               {color10}
color11               {color11}
color12               {color12}
color13               {color13}
color14               {color14}
color15               {color15}

# --- Starship Prompt Bubbles ---
color255              {surface}
color254              {accent}
color253              {surface}
color252              {green}
color251              {surface}
color250              {yellow}
color249              {surface}
color248              {red}

color232              {fg}
color233              {bg}
color234              {fg}
color235              {bg}
color236              {fg}
color237              {bg}
color238              {fg}
color239              {bg}
color240              {fg}

# Matched with unthemed light/dark
color243              {accent}
color244              {red}
color245              {dim}

# --- UI Elements ---
active_tab_foreground   {bg}
active_tab_background   {accent}
inactive_tab_foreground {fg}
inactive_tab_background {surface}

active_border_color     {accent}
inactive_border_color   {dim}

# --- Marks ---
mark1_foreground        {bg}
mark1_background        {accent}
mark2_foreground        {bg}
mark2_background        {green}
mark3_foreground        {bg}
mark3_background        {yellow}
