color0 #4b444d
color1 #ffb4ab
color2 #e1b7f5
color3 #d3c0d8
color4 #f4b7b8
color5 #e1b7f5
color6 #d3c0d8
color7 #e9e0e7
color8 #978e98
color9 #ffb4ab
color10 #e1b7f5
color11 #d3c0d8
color12 #f4b7b8
color13 #e1b7f5
color14 #d3c0d8
color15 #e9e0e7

cursor                #e9e0e7
cursor_text_color     #161217
background            #161217
foreground            #e9e0e7
selection_foreground  #cec3ce
selection_background  #4b444d
active_border_color   #e1b7f5
inactive_border_color #4b444d
url_color             #e1b7f5

active_tab_foreground   #422255
active_tab_background   #e1b7f5
inactive_tab_foreground #cec3ce
inactive_tab_background #4b444d
cursor_trail_color      #cec3ce
