color0 #4d453f
color1 #ffb4ab
color2 #d4c4b7
color3 #cec5be
color4 #c8c7b8
color5 #d4c4b7
color6 #cec5be
color7 #e7e1df
color8 #998f87
color9 #ffb4ab
color10 #d4c4b7
color11 #cec5be
color12 #c8c7b8
color13 #d4c4b7
color14 #cec5be
color15 #e7e1df

cursor                #e7e1df
cursor_text_color     #141312
background            #141312
foreground            #e7e1df
selection_foreground  #d0c4bc
selection_background  #4d453f
active_border_color   #d4c4b7
inactive_border_color #4d453f
url_color             #d4c4b7

active_tab_foreground   #382f26
active_tab_background   #d4c4b7
inactive_tab_foreground #d0c4bc
inactive_tab_background #4d453f
cursor_trail_color      #d0c4bc
